### ISSUE TITLE
Claim: WARBLRB10k-10K Smartphone Recording Dataset

### ISSUE THREAD

**Issue by Rutam21** [DagsHub/audio-datasets#100]
### warblrb10k is a collection of 10,000 smartphone audio recordings from around the UK, crowdsourced by users of Warblr the bird recognition app.

Papers with Code- https://paperswithcode.com/dataset/warblrb10k
Dataset Homepage- https://dcase.community/challenge2018/task-bird-audio-detection

- I will add the Dataset to DagsHub.

**Comment by meganS925** [comment]
Hey @Rutam21! Thanks for your contribution. 
A small note: please modify your read me to provide more metadata
