### ISSUE TITLE
Grammatical errors in URDU-Dataset documentation 

### ISSUE THREAD

**Issue by idivyanshbansal** [DagsHub/audio-datasets#8]
Fix grammatical errors in the readme file of URDU-Dataset.

**Comment by kingabzpro** [comment]
The issue is not required you have already corrected the mistakes. Please read rules properly if you contribute to Hacktoberfest 2021 https://github.com/DAGsHub/audio-datasets/blob/main/README.md

**Comment by idivyanshbansal** [comment]
> The issue is not required as you have already corrected the mistakes. Please read rules properly if you want to contribute in Hacktoberfest 2021 https://github.com/DAGsHub/audio-datasets/blob/main/README.md

Okay sir, then I should close this issue ?
